### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by stephypocky**
Stephy / 王雅筠
http://18.179.220.7:3000/
http://18.179.220.7:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Aspect ratio of any images in your page should keep the same as original ones.

**Comment by stephypocky** [comment]
The image ratio has been fixed by adding an object-fit attribute. 
http://18.179.220.7:3000/
http://18.179.220.7:3000/attraction/10

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Comment by stephypocky** [comment]
resent the review request. sorry about that.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
