### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by stephypocky**
Stephy / 王雅筠
http://18.179.220.7:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your layout will exceed screen width in all screen width<1920px, where we can see the horizontal scroll bar.

**Comment by stephypocky** [comment]
The RWD layout has been fixed without a horizontal scroll underneath. And the javascript code has been tidied up. 
http://18.179.220.7:3000/

**Comment by stephypocky** [comment]
Hi Peng,  I would like to confirm if the pull request has been approved as I saw my name shown on the list of tasks accomplished. Cheers. :)

**Review by cwpeng — APPROVED** [review]
OK. Sorry for forgetting to approve your PR.

**Pull request merged**
